# Generated by Django 4.0 on 2022-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
