# Generated by Django 4.0 on 2022-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediaitem_likes_mediaitem_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
