# Generated by Django 4.0 on 2022-01-12 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_mediaitemreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='likes',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
