# Generated by Django 4.0 on 2022-01-17 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_mediaitem_likes_mediaitemlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MediaItemLike',
        ),
    ]
