# Generated by Django 4.0 on 2022-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mediaitem_likes_delete_mediaitemlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
