# Generated by Django 4.0 on 2022-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_maincategory_title_alter_mediaitem_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitemreview',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='like_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
