# Generated by Django 4.0 on 2022-01-20 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_mediaitemreview_options_mediaitem_like_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
