# Generated by Django 4.0 on 2022-01-20 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_mediaitem_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='like_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 14, 46, 44, 809253, tzinfo=utc)),
        ),
    ]
