# Generated by Django 4.0 on 2022-01-21 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_mediaitem_like_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='like_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 10, 30, 8, 936526, tzinfo=utc)),
        ),
    ]
