# Generated by Django 4.0 on 2022-01-21 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_about_alter_mediaitem_like_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='like_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 10, 34, 16, 494066, tzinfo=utc)),
        ),
    ]
