# Generated by Django 4.0 on 2022-01-21 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_about_image_alter_about_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='like_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 23, 27, 33, 524889, tzinfo=utc)),
        ),
    ]
