# Generated by Django 4.0 on 2022-01-21 23:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_mediaitem_like_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='like_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 23, 29, 0, 779761, tzinfo=utc)),
        ),
    ]
