# Generated by Django 4.0 on 2022-01-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0016_alter_mediaitem_like_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitemreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='auth.user'),
        ),
    ]
