# Generated by Django 4.0 on 2022-02-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_mediaitemreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitemreview',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
