# Generated by Django 4.0 on 2022-05-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_mediaitemreview_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='body_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
